//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Market.DbModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLocation
    {
        public int CLID { get; set; }
        public Nullable<int> CClientID { get; set; }
        public string CLName { get; set; }
        public string CLAddress { get; set; }
        public string CLCity { get; set; }
        public string CLState { get; set; }
        public string CLZip { get; set; }
        public string CLCountry { get; set; }
        public string CLPhone { get; set; }
        public string CLComments { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
