//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Market.DbModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int IID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public Nullable<int> Warehouse { get; set; }
        public Nullable<System.DateTime> AvailabiltyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Comments { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
