//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Market.DbModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCR
    {
        public int OID { get; set; }
        public string record_no { get; set; }
        public string version { get; set; }
        public string format { get; set; }
        public string cust_ref { get; set; }
        public string cust_po_no { get; set; }
        public string po_number { get; set; }
        public string carrier { get; set; }
        public string ship_code { get; set; }
        public string ship_code_description { get; set; }
        public string working_ship_code { get; set; }
        public string cust_company { get; set; }
        public string cust_title { get; set; }
        public string cust_first_name { get; set; }
        public string cust_last_name { get; set; }
        public string cust_address_1 { get; set; }
        public string cust_address_2 { get; set; }
        public string cust_address_3 { get; set; }
        public string cust_city { get; set; }
        public string cust_state { get; set; }
        public string cust_zip { get; set; }
        public string cust_country { get; set; }
        public string cust_phone { get; set; }
        public string cust_e_mail { get; set; }
        public string ship_company { get; set; }
        public string ship_title { get; set; }
        public string ship_first_name { get; set; }
        public string ship_last_name { get; set; }
        public string ship_address_1 { get; set; }
        public string ship_address_2 { get; set; }
        public string ship_address_3 { get; set; }
        public string ship_city { get; set; }
        public string ship_state { get; set; }
        public string ship_zip { get; set; }
        public string ship_country { get; set; }
        public string ship_phone { get; set; }
        public string ship_e_mail { get; set; }
        public string ship_address_type { get; set; }
        public string customer_id { get; set; }
        public string order_date { get; set; }
        public string sub_total { get; set; }
        public string order_discount { get; set; }
        public string sales_tax { get; set; }
        public string shipping_handling { get; set; }
        public string grand_total { get; set; }
        public string balance { get; set; }
        public string currency_code { get; set; }
        public string credit_card_no { get; set; }
        public string expiration_date { get; set; }
        public string order_source { get; set; }
        public string promo_code { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
