//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Market.DbModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProcessLog
    {
        public System.DateTime OrderFetchDT { get; set; }
        public string OrderFetchStatus { get; set; }
        public Nullable<short> OrderCount { get; set; }
        public Nullable<System.DateTime> ProcessStartDT { get; set; }
        public Nullable<System.DateTime> ProcessEndDT { get; set; }
    }
}
