//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Market.DbModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OID { get; set; }
        public int OEmpID { get; set; }
        public int OClientID { get; set; }
        public System.DateTime ODate { get; set; }
        public Nullable<int> OType { get; set; }
        public Nullable<System.DateTime> OShipStartDate { get; set; }
        public Nullable<System.DateTime> OShipCancelDate { get; set; }
        public string OPOID { get; set; }
        public Nullable<int> OClientLocation { get; set; }
        public Nullable<decimal> OTaxes { get; set; }
        public string OPaymentType { get; set; }
        public string OPaymentTerms { get; set; }
        public Nullable<System.DateTime> OPaidDate { get; set; }
        public string ONotes { get; set; }
        public string OShipNotes { get; set; }
        public string OStatusID { get; set; }
        public string OExSource { get; set; }
        public string OExSourceOrg { get; set; }
        public string OExSourceID { get; set; }
        public Nullable<decimal> OProcessFee { get; set; }
        public Nullable<float> OProcessFeeAddPct { get; set; }
        public Nullable<float> OTotalTaxPct { get; set; }
        public Nullable<decimal> OSHFee { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual OrderCR OrderCR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual RefOrderType RefOrderType { get; set; }
    }
}
