//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Market.DbModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsImport
    {
        public int ID { get; set; }
        public Nullable<int> BID { get; set; }
        public string PID { get; set; }
        public string SKUCode { get; set; }
        public string UPCCode { get; set; }
        public string PName { get; set; }
        public string VendorName { get; set; }
        public string PColor { get; set; }
        public string PSize { get; set; }
        public Nullable<short> PCategory { get; set; }
        public string PSubCategory { get; set; }
        public Nullable<int> NRFColorCodeID { get; set; }
        public Nullable<int> SID { get; set; }
        public string PDescription { get; set; }
        public string PSpecs { get; set; }
        public string PCoutryofOrigin { get; set; }
        public bool PDiscontinued { get; set; }
        public string PFOBCost { get; set; }
        public string PLandedCost { get; set; }
        public string PWholesalePrice { get; set; }
        public string PMSRPPrice { get; set; }
        public string PPicture { get; set; }
        public Nullable<int> ProductStatusId { get; set; }
        public Nullable<int> VID { get; set; }
        public Nullable<int> ColorCategoryId { get; set; }
        public string ShopifyPicUrl { get; set; }
        public string Brand_Category { get; set; }
        public string Message { get; set; }
    }
}
