//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Market.DbModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefNRFColorCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefNRFColorCode()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int NRFColorCodeID { get; set; }
        public Nullable<int> NRFColorCode { get; set; }
        public string NRFColorName { get; set; }
        public Nullable<int> ColorCategoryID { get; set; }
    
        public virtual ColorCategory ColorCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
