//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Market.DbModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Report
    {
        public string Group_By { get; set; }
        public string Display { get; set; }
        public string Title { get; set; }
        public string Filter_Row_Source { get; set; }
        public bool Default { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
